### ISSUE TITLE
Untranslated Label, cannot be used

### ISSUE THREAD

**Issue by Robdebert** [Percha/com_fieldsattachsearch#1]
When trying to setup a new menuitem for this component, i cannot save it, because of an error-message: "Field required: COM_FIELDSATTACHSEARCH_SEARCH_LABEL"

Also i cannot see any values here that could be adjusted.

See attached screenshot. Clear install, nothing modified.
![fieldsattachsearch](https://cloud.githubusercontent.com/assets/1737455/5920265/a96d0a94-a63b-11e4-9b05-968dd2a78418.png)

**Comment by graredcr** [comment]
Sorry it is a DEPRECATED feature. I will remove it.

Cristian

**Comment by Robdebert** [comment]
After adding a now search via the component, i can now select it in the menuitem. 
Perhaps a message would be cool, saying "You have to create a search in the component first, then select it here".

**Comment by graredcr** [comment]
The search for fieldsattach is in other component. this feature , now not work well.

**Comment by Robdebert** [comment]
Ah ok. So this component should not be used? 

I downloaded it, because the default component for fieldsattachment tells me this:
"Extra fields filter search (DEPRECASED!!! NOT USE IT!! DOWNLOAD THE SEARCH COMPONENT FOR J3)" 

:-)

**Comment by graredcr** [comment]
SORRY yes it's this component!! But you need the plugin for create a SQL, this is only for configure.

**Comment by graredcr** [comment]
More info in fieldsattach.com
